config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get '/pages/:permalink' => "pages#permalink", as: "permalink"
  # get 'home/index'
  root to: "home#index"
  # get 'production_companies/index'
  # get 'production_companies/show'
  # get 'movies/index'
  # get 'movies/show'
  resources :movies, only: [:index, :show]
  resources :production_companies, only: [:index, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :production_company
  validates :title, :year, :duration, :description, :average_vote, presence: true
  validates :title, uniqueness: true
  validates :year, :duration, numericality: {only_integer: true}
  validates :average_vote, numericality: true

  has_many :movie_genres
  has_many :genres, through: :movie_genres
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title,:content, :permalink, presence: true
end

app/models/production_company.rb
class ProductionCompany < ApplicationRecord
  has_many :movies
  validates :name, uniqueness: true

  def self.orderd_by_movies
    self.select("production_companies.*")
    .select("COUNT(production_companies.id) as movie_count")
    .left_joins(:movies)
    .group("production_companies.id")
    .order("movie_count DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :cms_pages

  def cms_pages
    Page.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.includes(:production_company)
                    .order("average_vote DESC")
                    .limit(10)
    @production_companies = ProductionCompany.orderd_by_movies.limit(10)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.includes(:production_company).all.order("average_vote DESC")
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  http_basic_authenticate_with name: "user", password: "password", except: :show

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
      # @page = Page.find_by(permalink: params[:permalink])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :content, :permalink)
    end
end

app/controllers/production_companies_controller.rb
class ProductionCompaniesController < ApplicationController
  def index
    # @production_companies = ProductionCompany.all
    # @production_companies = ProductionCompany.select("production_companies.*")
    #                                           .select("COUNT(production_companies.id) as movie_count")
    #                                           .left_joins(:movies)
    #                                           .group("production_companies.id")
    #                                           .order("movie_count DESC")
    @production_companies = ProductionCompany.orderd_by_movies
  end

  def show
    @production_company = ProductionCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/common/_footer.html.erb
<footer>
  <p>
    <em>Copywrong IMDB 2024</em>
  </p>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Top 100 Movies", movies_path %></li>
    <li><%= link_to "Top Production Companies", production_companies_path %></li>
    <li><%= link_to 'About the Data', permalink_path('about') %></li>
    <li><%= link_to 'Contact Us', permalink_path('contact') %></li>
    <% cms_pages.each do |page| %>
      <li>
        <%= link_to page.title, permalink_path(page.permalink) %>
      </li>
    <% end %>
  </ul>
</footer>

app/views/home/index.html.erb
<h1>Home#index</h1>

<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 100 Movies</h2>
    <ol class="ml-5">
      <% @movies.each do |movie| %>
        <li>
          <%= link_to movie.title, movie %>
          <em>by <%= link_to movie.production_company.name %></em>
        </li>
      <% end %>
    </ol>
    <p class="mt-5">
      <strong>
        <%= link_to '😀 See the Top 100 Movies', movies_path %>
      </strong>
    </p>
  </div>

  <div class="column">
    <h2 class="title is-2"> Top 10 Production Companies </h2>
    <ol class="ml-5">
      <% @production_companies.each do |p| %>
        <li>
          <%= link_to p.name, p %>
        </li>
      <% end %>
    </ol>
    <p class="mt-5">
      <strong>
        <%= link_to '😀 See the Top Production Companies', production_companies_path %>
      </strong>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " -" if content_for?(:html_title) %> Top 100 Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">
        <h1 class="title is-1">Top Movies From IMDB</h1>
      </div>

    <%= yield %>
    <% if controller_name == 'home' %>
      <p>There's no place like home</p>
    <% else %>
      <%= render partial: 'common/footer' %>
    <% end %>
    </section>
  </body>
</html>

app/views/movies/_movie.html.erb
<h2 class="title is-4"><%= movie.title %></h2>
<article class="message is-dark">
  <div class="message-header">
    <p>Description</p>
  </div>
  <div class="message-body">
      <%= movie.description %>
  </div>
</article>

<progress class="progress is-info" value="<%= movie.average_vote %>" max="10">
  <%= movie.average_vote %>
</progress>

<p>
  <strong>
    Rating:
  </strong>
  <%= movie.average_vote %>
</p>

<p>
  <strong>
    Genres:
  </strong>
  <%= movie.genres.map(&:name).join(", ") %>
</p>

<p>
  <strong>
    Realease Year
  </strong>
  <%= movie.year %>
</p>

<p>
<strong>
  Production Company
</strong>
<%= link_to movie.production_company.name, movie.production_company %>
</p>

app/views/movies/index.html.erb
<h2>Top 100 Movies</h2>
<ol>
  <%#= render partial: @movies, locals: {show_link: false} %>
<%= render @movies %>
</ol>

app/views/movies/show.html.erb
<% content_for(:html_title) {@movie.title} %>
<%= render @movie %>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :permalink, style: "display: block" %>
    <%= form.text_field :permalink %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= page.content %>
  </p>

  <p>
    <strong>Permalink:</strong>
    <%= page.permalink %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", permalink_path(page.permalink) %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/permalink.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page.permalink) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/production_companies/_production_company.html.erb
<% @production_companies.each do |c| %>
  <li>
    <%= link_to c.name, c %>
    <em>(<%= pluralize c.movie_count , "Top Movie"%>)</em>
  </li>
<% end %>

app/views/production_companies/index.html.erb
<h2 class="title is-2">Production Companies</h2>
<ol>
  <%= render @production_companies %>
</ol>

app/views/production_companies/show.html.erb
<h2 class="title is-2">
  <%= @production_company.name %>
</h2>
<p class="mb-4">
  This production company made
  <%= @production_company.movies.count %> of the top 100 movies.
</p>

<h3 class="title is-6">
  Movies made by <%= @production_company.name %>
  <ul>
    <% @production_company.movies.each do |m| %>
      <li>
        <%= link_to m.title, m %> with a rating of
        <%= m.average_vote %> / 10
      </li>
    <% end %>
  </ul>
</h3>